from enum import Enum

class Lang(str, Enum):
    RU = "ru"
    EN = "en"
    CN = "cn"  # ← добавляем китайский


STRINGS = {
    "ru": {
        "app.title": "Распределение расстояний между частицами в сосудах различной формы",
        "menu.title": "Распределение расстояний между частицами",
        "menu.subtitle": "в сосудах различной формы",
        "menu.start": "Начать",
        "menu.authors": "Об авторах",
        "menu.theory": "Теория",
        "menu.exit": "Выход",

        "vessel.rect": "Прямоугольник",
        "vessel.circle": "Круг",
        "vessel.poly": "Многоугольник",

        "sim.settings": "Настройки",
        "sim.N": "N",
        "sim.N.unit": "1-100",
        "sim.N.help": "Число частиц",
        "sim.R": "R",
        "sim.R.unit": "0.5-10",
        "sim.R.help": "Радиус частицы",
        "sim.T": "T",
        "sim.T.unit": "0.1-50",
        "sim.T.help": "Температура",
        "sim.m": "m",
        "sim.m.unit": "0.01-100",
        "sim.m.help": "Масса частицы",
        "sim.collisions": "Столкновения частиц",
        "sim.pot": "Тип",
        "sim.pot.help": "Тип парного потенциала",
        "sim.eps": "ε",
        "sim.eps.unit": "0-100",
        "sim.eps.help": "Энергетический масштаб",
        "sim.sigma": "σ",
        "sim.sigma.unit": "1-30",
        "sim.sigma.help": "Расстояние ЛД",
        "sim.De": "De",
        "sim.De.unit": "0-100",
        "sim.De.help": "Глубина ямы Морзе",
        "sim.a": "a",
        "sim.a.unit": "0.01-5",
        "sim.a.help": "Жёсткость потенциала Морзе",
        "sim.r0": "r₀",
        "sim.r0.unit": "1-20",
        "sim.r0.help": "Расстояние Морзе",
        "sim.vessel": "Сосуд",
        "sim.vessel.help": "Форма сосуда",
        "sim.interact": "Взаимодействия",
        "sim.interact.unit": "к-я итерация",
        "sim.bins": "Бины",
        "sim.bins.help": "Бины",

        "sim.btn.draw": "Рисовать",
        "sim.btn.clear": "Очистить",
        "sim.btn.pause": "Пауза",
        "sim.btn.start": "Старт",
        "sim.btn.apply": "Применить",
        "sim.btn.back": "Назад",
        "sim.btn.collapse": "Свернуть",
        "sim.btn.expand": "Развернуть",
        "sim.top.settings": "Настройки",
        "sim.anim.title": "Область моделирования",

        "sim.hist.x": "Распределение X",
        "sim.hist.y": "Распределение Y",
        "sim.hist.r": "Распределение расстояний",
        "sim.hist.title": "Гистограммы",

        "sim.btn.select_particles": "Выбор частиц",
        "sim.btn.cancel_selection": "Отменить",

        "sim.histograms.title": "Гистограммы",
        "sim.display_mode.distance": "Расстояние",
        "sim.display_mode.projections": "Проекции на оси",
        "sim.display_mode.signed": "Расстояние со знаком",
        "sim.btn.reset_data": "Сбросить",
        "sim.btn.reset_data.tooltip": "Очистить все накопленные данные гистограмм",

        "authors.title": "Команда разработчиков",
        "authors.name1": "Енягин Станислав",
        "authors.name2": "Кожемякова Елизавета",
        "boss": "Научный руководитель: Чичигина Ольга Александровна",
        "authors.back": "Вернуться",
    },
    "en": {
        "app.title": "Distribution of Distances Between Particles in Vessels of Various Shapes",
        "menu.title": "Distribution of Particle Distances",
        "menu.subtitle": "in vessels of various shapes",
        "menu.start": "Start Simulation",
        "menu.authors": "Authors",
        "menu.theory": "Theory",
        "menu.exit": "Exit",

        "vessel.rect": "Rectangle",
        "vessel.circle": "Circle",
        "vessel.poly": "Polygon",

        "sim.settings": "Simulation settings",
        "sim.N": "N",
        "sim.N.unit": "5-100",
        "sim.N.help": "Number of particles",
        "sim.R": "R",
        "sim.R.unit": "0.5-10",
        "sim.R.help": "Particle radius",
        "sim.T": "T",
        "sim.T.unit": "0.1-50",
        "sim.T.help": "Temperature",
        "sim.m": "m",
        "sim.m.unit": "0.01-100",
        "sim.m.help": "Particle mass",
        "sim.collisions": "Particle collisions",
        "sim.pot": "Type",
        "sim.pot.help": "Pair potential type",
        "sim.eps": "ε",
        "sim.eps.unit": "0-100",
        "sim.eps.help": "Energy scale",
        "sim.sigma": "σ",
        "sim.sigma.unit": "1-30",
        "sim.sigma.help": "LJ distance",
        "sim.De": "De",
        "sim.De.unit": "0-100",
        "sim.De.help": "Morse well depth",
        "sim.a": "a",
        "sim.a.unit": "0.01-5",
        "sim.a.help": "Morse stiffness",
        "sim.r0": "r₀",
        "sim.r0.unit": "1-20",
        "sim.r0.help": "Morse distance",
        "sim.vessel": "Vessel",
        "sim.vessel.help": "Vessel shape",
        "sim.interact": "Interactions",
        "sim.interact.unit": "th iter",
        "sim.bins": "Bins",
        "sim.bins.help": "Bins",

        "sim.btn.draw": "Draw",
        "sim.btn.clear": "Clear",
        "sim.btn.pause": "Pause",
        "sim.btn.start": "Start",
        "sim.btn.apply": "Apply",
        "sim.btn.back": "Back",
        "sim.btn.collapse": "Collapse",
        "sim.btn.expand": "Expand",
        "sim.top.settings": "Settings",
        "sim.anim.title": "Simulation area",

        "sim.hist.x": "Distribution of X",
        "sim.hist.y": "Distribution of Y",
        "sim.hist.r": "Distribution of pair distances",
        "sim.hist.title": "Histograms",

        "sim.btn.select_particles": "Select particles",
        "sim.btn.cancel_selection": "Cancel",

        "sim.histograms.title": "Histograms",
        "sim.display_mode.distance": "Distance",
        "sim.display_mode.projections": "Projections",
        "sim.display_mode.signed": "Signed distance",
        "sim.btn.reset_data": "Reset",
        "sim.btn.reset_data.tooltip": "Clear all accumulated histogram data",

        "menu.authors": "Authors",
        "authors.title": "Development Team",
        "authors.name1": "Stanislav Eniagin",
        "authors.name2": "Elizaveta Kozhemyakova",
        "boss": "Scientific supervisor: Olga Aleksandrovna Chichigina",
        "authors.back": "Back",
    },
    "cn": {
        "app.title": "各种形状容器中粒子间距离分布",
        "menu.title": "粒子距离分布",
        "menu.subtitle": "在各种形状容器中",
        "menu.start": "开始模拟",
        "menu.authors": "关于作者",
        "menu.theory": "理论",
        "menu.exit": "退出",

        "vessel.rect": "矩形",
        "vessel.circle": "圆形",
        "vessel.poly": "多边形",

        "sim.settings": "模拟设置",
        "sim.N": "N",
        "sim.N.unit": "5-100",
        "sim.N.help": "粒子数量",
        "sim.R": "R",
        "sim.R.unit": "0.5-10",
        "sim.R.help": "粒子半径",
        "sim.T": "T",
        "sim.T.unit": "0.1-50",
        "sim.T.help": "温度",
        "sim.m": "m",
        "sim.m.unit": "0.01-100",
        "sim.m.help": "粒子质量",
        "sim.collisions": "粒子碰撞",
        "sim.pot": "类型",
        "sim.pot.help": "对势类型",
        "sim.eps": "ε",
        "sim.eps.unit": "0-100",
        "sim.eps.help": "能量尺度",
        "sim.sigma": "σ",
        "boss": "奇奇吉娜·奥尔加·亚历山德罗夫娜",
        "sim.sigma.unit": "1-30",
        "sim.sigma.help": "LJ特征距离",
        "sim.De": "De",
        "sim.De.unit": "0-100",
        "sim.De.help": "Morse势阱深度",
        "sim.a": "a",
        "sim.a.unit": "0.01-5",
        "sim.a.help": "Morse刚度",
        "sim.r0": "r₀",
        "sim.r0.unit": "1-20",
        "sim.r0.help": "平衡距离 (Morse)",
        "sim.vessel": "容器",
        "sim.vessel.help": "容器形状",
        "sim.interact": "相互作用",
        "sim.interact.unit": "第 次迭代",
        "sim.bins": "分箱",
        "sim.bins.help": "直方图的分箱数量",

        "sim.btn.draw": "绘制多边形",
        "sim.btn.clear": "清除多边形",
        "sim.btn.pause": "暂停",
        "sim.btn.start": "开始",
        "sim.btn.apply": "应用",
        "sim.btn.back": "返回",
        "sim.btn.collapse": "折叠",
        "sim.btn.expand": "展开",
        "sim.top.settings": "设置",
        "sim.anim.title": "模拟区域",

        "sim.hist.x": "X分布",
        "sim.hist.y": "Y分布",
        "sim.hist.r": "距离分布",
        "sim.hist.title": "直方图",

        "sim.btn.select_particles": "选择粒子",
        "sim.btn.cancel_selection": "取消选择",

        "sim.histograms.title": "直方图",
        "sim.display_mode.distance": "常规距离",
        "sim.display_mode.projections": "投影",
        "sim.display_mode.signed": "带符号距离",
        "sim.btn.reset_data": "重置数据",
        "sim.btn.reset_data.tooltip": "清除所有累积的直方图数据",

        "menu.authors": "关于作者",
        "authors.title": "开发团队",
        "authors.name1": "叶尼亚金·斯坦尼斯拉夫",
        "authors.name2": "科热米亚科娃·伊丽莎白",
        "boss": "科学指导：奇奇吉娜·奥尔加·亚历山德罗夫娜",
        "authors.back": "返回",
    },
}